version: '3.7'
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  migrator:
    image: migrate/migrate
    restart: "no"
    volumes:
      - ./backend/db_migrations:/migrations
    entrypoint: >
      sh -c "migrate -path=/migrations -database=postgres://postgres:${POSTGRES_PASSWORD}@db/postgres?sslmode=disable up"
    env_file:
      - .env
    depends_on:
      - db

  graphql:
    build:
      context: backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db/?sslmode=disable
      ENABLE_SSH: "false"
      OWNER_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db/?sslmode=disable
      PG_HOST: db
    depends_on:
      - db

  frontend:
    build:
      context: mealplanner-ui
    ports:
      - "3000:80"
    depends_on:
      - graphql

  admin:
    build:
      context: admin-ui
    ports:
      - "2000:80"
    depends_on:
      - graphql

volumes:
  pgdata:
