drop schema if exists app_private, app cascade;
\i setup-user.sql
\i 000-common-utils.sql
\i 001-auth-system.sql
\i 002-nutrition.sql
\i 003-product.sql
\i 004-meal.sql
\i 005-measure.sql
\i 006-meal-plan.sql
\i 007-meal-plan-entry.sql
\i 009-authorize-meal-designer.sql
\i 010-shopping-list.sql
\i 011-authorize-admin.sql
\i 012-duplicate-meal-plan.sql
\i 013-add-email-and-role-to-person.sql
\i 014-reset-password.sql
