-- GREENER VILLAGE RECIPES FOR THE TABLE MEAL:
INSERT INTO
      app.meal (code,      name_en,                     name_fr,                                  tags,
	              description_en,
                description_fr,
		            categories,
                photo_url,
                video_url,
                method,
		            cooking_duration, total_cost, serving_cost,
		            tips,
		            servings_size, servings_size_unit, serves)
        VALUES ('c_sandwiches',
                'Chicken Salad Sandwich',                 'Sandwich à la salade de poulet',         '{"sandwiches"}',
                '',
                '',
                '{}',
                'https://hips.hearstapps.com/del.h-cdn.co/assets/17/32/2048x1024/landscape-1502305153-chicken-salad-sandwich-delish-1.jpg?resize=980:*',
                'https://www.youtube.com/watch?v=Yv9Hve2UzR0',
                'Heat oven to 325f
                1.	Rub the oil over the chicken thighs and sprinkle with a little salt and pepper.
                2.	Place the chicken thighs on a baking sheet and bake until the chicken is thoroughly cooked (approx. 30 minutes. Check for “doneness” by cutting chicken or using a digital thermometer*)
                3.	When cooked, cool slightly, cover and place in refrigerator for use.
                4.	When cooled, chop the chicken into small dice and place in bowl. Add mayonnaise and salt and pepper and mix together well.
                5.	Lay out four (4) slices of bread on a cutting board or counter top and divide and spread the filling between two (2) slices of bread. Top each with the remaining slices. Cut diagonally, wrap well and refrigerate for use.',
                40,               2.80,       1.40,
                '1. Try adding 2 Tbsp. (30 ml) of finely chopped celery, green onion and / or onion to the chicken mixture.
                2. The number of sandwiches made will depend on the amount of filling placed on the bread.
                3. 6 ozs W of chicken will shrink to approximately 4 ozs W after baking.
                4. *If you have a digital thermometer, the chicken is cooked when the internal temperature reads 165 f.',
                0,             '',                 2),

               ('e_sandwiches',
                'Egg Salad Sandwich',                     'Sandwich à la salade dœufs',             '{"sandwiches"}',
                '',
                '',
                '{}',
                'https://www.somewhatsimple.com/wp-content/uploads/2019/05/egg_salad_1.jpg',
                'https://www.youtube.com/watch?v=3X6eP273RoI',
                '1. Place the eggs in a saucepan and cover with cold water. Bring to a boil and continue cooking for approximately 10 minutes.
                2. Remove from the heat and run cold water over the eggs until fully cooled.(eggs can be cooked the day before use, cooled and placed in the refrigerator)
                3. Shell the eggs and into a bowl, grate the eggs using a grater, or, mash using a fork.
                4. Add the mayonnaise, salt and pepper and mix gently together.
                5. Lay out six (6) pieces of bread on a cutting board or counter top and divide and spread the filling between three (3) slices of bread. Top each with the remaining slices. Cut diagonally, wrap well and refrigerate for use.',
                20,               1.55,       .52,
                '1. Try adding 1 ½ Tbsp. (22.5 ml) of finely chopped celery, green onion or onion to the egg mixture.
                2. The number of sandwiches made will depend on the amount of filling placed on the bread.',
                0,             '',                 3),

               ('mm_baked_beans',
                'Baked Beans',                             'Haricots au lard',                       '{"main_meal", "baked_beans"}',
                '',
                '',
                '{}',
                'https://i2.wp.com/lifemadesimplebakes.com/wp-content/uploads/2015/07/Moms-Oven-Baked-Beans-1.jpg',
                'https://www.youtube.com/watch?v=ijRAojGPLXg',
                '1. Place the beans in a large bowl and cover with cold water. Soak overnight. Add more water as necessary to ensure that the beans stay covered. In the morning drain and rinse the beans.
                2. Preheat the oven to 250f / 120c and place the oven rack in the middle position.
                3. Combine all of the ingredients except the salt, in a large ovenproof Dutch oven or a large ovenproof saucepan that has a tight fitting cover. Add pepper to taste. Add enough water to cover the beans by 2” / 5cm and bring to a boil.
                4. Remove from the stove. Cover the Dutch oven and place in oven.
                5. Bake for about 7 hours, stirring every hour until the beans are tender. Adding more water as needed during cooking.
                6. Just prior to beans being ready, remove about ½ cup of beans, mash and return to pot.',
                480,               0,          0,
                'Do not add the salt until the beans are almost done as this tends to toughen beans.',
                0,              '',                 0),

               ('s_starches',
                'Baked Potatoes',                          'Pommes de terre cuites',                 '{"sides", "starches"}',
                '',
                '',
                '{}',
                'https://keviniscooking.com/wp-content/uploads/2020/04/The-Perfect-Baked-Potato-square.jpg',
                'https://www.youtube.com/watch?v=zbqUsWndSUg',
                'Preheat oven to 350f
                1. Wash and scrub the potatoes. Leave wet. Sprinkle with salt. Cut a slit in the top of the potato and place on a parchment lined baking sheet.
                2. Bake at 350f for about an hour until a toothpick inserted in the potato offers no resistance. The potato skin should be dry and slightly crisp.
                3. When cooked, press the ends of the potato together to open the slit and expose the potato.',
                65,                0,          0,
                '1. Use a potato such as Russet, which will produce a loose, mealy texture when baked. New potatoes will not produce this light, mealy texture.
                2. Through a process called “osmosis” the salt on the skin will be drawn into the potato. No additional salt should be needed.
                3. To make this potato more of a meal, top with one or more of the following: butter, small steamed broccoli florets, cheese sauce, grated cheese, bacon bits, sour cream or chopped green onions',
                0,              '',                 4),

               ('mm_fish',
                'Battered Fish',                           'Poisson pané',                           '{"main_meal", "fish"}',
                '',
                '',
                '{}',
                'https://tmbidigitalassetsazure.blob.core.windows.net/rms3-prod/attachments/37/1200x1200/Lemon-Batter-Fish_EXPS_HCA19_10179_E06_22_5b.jpg',
                'https://www.youtube.com/watch?v=bVPWAT0W8GM',
                '1. In a large bowl, add the flour and season with salt and pepper. Add the water, buttermilk and a “splash” of soda water.
                2. Mix all ingredients until smooth. The batter will be quite thin.
                3. Heat enough oil, about 6 cups / 1 ½ litres in a medium heavy saucepan or deep fryer until the *temperature reaches 325 – 350f.
                4. Place the all purpose flour in a bowl and coat the fish pieces. Dip the fish into the batter and gently lower into the hot oil and fry, turning, for about 8 – 10 minutes until golden brown. Reduce the time if the fish fillets are thin.
                5. Serve the fish with Tartare sauce.',
                20,                0,          0,
                '1. *A digital thermometer is essential if using a saucepan to heat the oil, in order to check the temperature of the oil and to make sure that it does not overheat and become a fire risk. Be sure to remove the oil from the stove as soon as you have finished cooking the fish. The oil, when cooled, can be strained through cheesecloth, placed in a covered container, refrigerated and kept until the next time you deep fry.
                2. Buttermilk: No need to buy. Just mix 1 cup of milk with 1 Tbsp of white vinegar, mix, let stand for 5 minutes and use in recipe(s)
                3. Self Rising flour: To make your own, just mix 1 ¼  cups of all purpose flour with 1 ¾  Tsp. of baking powder and ½ Tsp. of salt.',
                0,              '',                 4),

               ('mm_beef',
                'Beef Stew',                               'Ragoût de bœuf',                         '{"main_meal", "beef"}',
                '',
                '',
                '{}',
                'https://www.jessicagavin.com/wp-content/uploads/2020/12/beef-stew-14-1200.jpg',
                'https://www.youtube.com/watch?v=6HyT4aHvN7s',
                '1. Place the flour in a bowl and add the beef. Mix well to coat the beef. Remove the beef from the flour shaking to remove any excess flour.
                2. Heat the oil in a heavy bottomed oven proof pan or Dutch oven over medium high heat and, in batches, brown the beef cubes on all sides. As they brown transfer them to a bowl.
                3. Into the same pot that you browned the beef in, add the carrots, onion, celery and vinegar. Fry vegetables until softened. Scrape any burnt “bits” from the bottom of the pan with a wooden spoon. Add the garlic, if using and fry for a further minute.
                4. Add the tomato paste and stir well for about 1 minute. Add the beef and any juices that have accumulated in the bowl. Add the heated beef broth, the water, bay leaf and thyme. Season with salt and pepper. While stirring, bring to a boil. Cover the pan and place in a 325-f oven for about 2 hours.
                5. Remove the pot from the oven and add the potatoes. Stir to mix. Cover and place pot back in the oven for about 1 hour or until the vegetables, meat and potatoes are tender and the sauce has thickened. Taste and adjust the seasonings if necessary.',
                0,                 0,          0,
                'This stew freezes well in an airtight container. Remove the potatoes prior to freezing as they don’t freeze well.',
                0,              '',                 8),

               ('mm_beef_side',
                'Beefaroni',                               'Beefaroni',                              '{"main_meal", "beef"}',
                'Macaroni, Beef and Tomato casserole',
                'Casserole de macaronis, bœuf et tomates',
                '{}',
                'https://www.thetravelpalate.com/wp-content/uploads/2021/04/beefaroni-22.jpg',
                'https://www.youtube.com/watch?v=pgRoIBEGTto',
                '1. Cook the macaroni noodles “al dente” (see below) in boiling water following package directions. Drain and rinse well under cold running water. Set aside in colander.
                2. In a large skillet or frying pan cook the beef until browned and no trace of pink remains. Drain the fat from the pan and discard.
                3. Add the diced onions and peppers and lightly fry for a few minutes. Add the garlic if using, tomato paste and stir to mix. Add the diced tomatoes and their juice, the vinegar, basil and oregano, salt and pepper and macaroni. Mix together well. Taste for seasoning and add extra salt and pepper if necessary. Cook over medium low heat, stirring occasionally for about 30 – 40 minutes until all flavours have blended. Or, place in greased baking dish, sprinkle lightly with grated cheese and bake in 325 f oven until heated through and cheese is lightly browned.',
                0,                 0,          0,
                'Al Dente or “to the tooth”, means the ideal consistency of cooked pasta. During cooking the macaroni will absorb some of the liquid. If you need to, add a little beef broth or water.',
                0,              '',                 0),

               ('desserts',
                'Bread And Butter Pudding',                'Pudding au pain et au beurre',           '{"desserts"}',
                '',
                '',
                '{}',
                'https://www.recipetineats.com/wp-content/uploads/2017/04/Bread-Butter-Pudding_4.jpg',
                'https://www.youtube.com/watch?v=9OgwCbDnJ90',
                'Preheat oven to 350f
                1.	Butter the bread, remove crusts and cut into two triangles.
                2.	Arrange half of the bread, buttered side up, in a greased 13” x 9” deep baking dish. Sprinkle with half of the raisin / sultana mix. Sprinkle with the sugar and cover with the remaining bread. Sprinkle with remaining raisin / sultana mix.
                3.	In a bowl, combine the eggs, milk, nutmeg and cinnamon and mix well. Pour over the bread.
                4.	Bake at 350f for about 35 – 40 minutes until the bread is lightly browned and the custard has set.
                5.	While the pudding is cooking, place the jam or marmalade in a small saucepan add a Tbsp. / 15ml of water and, over low heat, while stirring, melt the jam or marmalade. Remove the pudding from the oven and spread the warm jam or marmalade over the pudding. Serve warm.',
                55,                0,          0,
                'Serve with whipped cream or a lemon sauce.',
                0,              '',                 8),

               ('breakfast',
                'Breakfast Sandwich',                      'Sandwich déjeuner',                      '{"breakfast"}',
                '',
                '',
                '{}',
                'https://natashaskitchen.com/wp-content/uploads/2016/05/Breakfast-Sandwich-11.jpg',
                'https://www.youtube.com/watch?v=YMHGkBP2Liw',
                '1. Lightly toast the English muffin.
                2. Cook bacon until crisp. Set aside. Drain fat from pan.
                3. In the same pan place a very little butter or margarine and heat over medium heat. When heated, break the egg into the pan and break the yolk.  Sprinkle the egg very lightly with salt and pepper. Cover the frying pan with a lid allowing the yolk to firm up while the egg white cooks. When the yolk is almost firm and the white is cooked, flip the egg over. Continue cooking until the egg yolk has set.
                4. Place the cheese slice on the heated muffin bottom. Top with the egg and bacon.  Add the top half of the muffin.',
                10,                .90,        .90,
                '1. If making a breakfast sandwich with a sausage patty, fry the patty in a frying pan in a little oil. When cooked through, remove from pan and keep warm. Wipe out the pan with a cloth or paper towel before adding the egg.
                2. If preferred, a slice of ham can be substituted for the bacon or sausage.',
                0,              '',                 1),

               ('mm_chicken',
                'Chicken Fajita Wraps',                    'Wraps aux fajitas au poulet',            '{"main_meal","chicken"}',
                '',
                '',
                '{}',
                'https://karylskulinarykrusade.com/wp-content/uploads/2018/05/Crispy-Chicken-Fajita-Wrap-Feature-480x480.jpg',
                'https://www.youtube.com/embed/LHaFtvev3lc',
                '1. Heat the oil in a frying pan or skillet over medium heat. Season the chicken breasts or thighs with salt and pepper and fry gently until no longer pink (165 f). Remove from heat and keep warm.
                2. In the same pan, fry the onions and peppers until tender crisp. Add the taco mix and a little water and mix well. Simmer until flavours have blended, liquid has reduced and onion and peppers still retain some firmness. Taste for seasoning and adjust if necessary.
                3. Slice the chicken into thin slices.
                4. Warm the tortilla shells in a warm (225 f) oven for a minute or so and place on a flat working surface.
                5. Divide the sliced chicken and onion, pepper mix amongst the tortilla shells. Top each tortilla with the grated cheese and top each with a Tbsp. of sour cream and salsa.
                6. Fold shells over mixture, or roll.',
                0,                 0,          0,
                'Serve with Mexi rice and seasoned corn kernels for a full meal',
                0,              '',                 6),

               ('mm_fish_side',
                'Fish Cakes',                              'Galettes de poisson',                    '{"main_meal","fish"}',
                '',
                '',
                '{}',
                'https://www.recipetineats.com/wp-content/uploads/2021/07/Fish-Cakes_96.jpg',
                'https://www.youtube.com/watch?v=-LfiQMKH0qg',
                'To cook the fish, either 1. Gently fry in a butter and oil mix, or, 2. The better method is to poach the fish in simmering water with the addition of onion pieces, celery pieces, some lemon peel or juice and salt and pepper. Remove fish when “just done”. This should just take a few minutes. Remove from liquid, cool and flake.
                1. Place mashed potatoes, flaked fish, onions, beaten eggs, parsley, mustard powder, sour cream and salt and pepper in a large bowl and mix together until thoroughly mixed.
                2. Form the mixture into about 16 equal patties and roll in the breadcrumbs. Cover the patties and place in the refrigerator to “firm up” for an hour, or longer
                3. Heat the oil in a non-stick pan and fry the patties on each side for about 3 – 4 minutes until lightly browned. Serve immediately, accompanied with tartare sauce.',
                50,                0,          0,
                'The fish and potatoes can be prepared ahead of time, refrigerated and finished when ready to cook.',
                0,              '',                 8),

               ('s_starches_side',
                'Garlic Mashed Potatoes',                  'Purée de pommes de terre à lail',        '{"sides","starches"}',
                '',
                '',
                '{}',
                'https://natashaskitchen.com/wp-content/uploads/2021/11/Garlic-Mashed-Potatoes-5.jpg',
                'https://www.youtube.com/watch?v=g9pWsxEtiAg',
                '1. Place the potato chunks in cold water or under cold running water for about 20 minutes to remove some of the starch. Drain.
                2. Place the potatoes and garlic in cold water in a saucepan, add a little salt. Bring to the boil. Lower heat and simmer until potatoes are tender.
                3. Drain the potatoes and using a potato masher or “ricer” (see below) mash the potatoes. Add butter, cream or milk and white pepper to taste. Do not over mash the potatoes as this will toughen them. This is where the ricer is the best choice as the potatoes are only put through once and it eliminates any lumps of potato.',
                65,                0,          0,
                '',
                0,              '',                 0),

               ('s_chowders',
                'Hamburger Soup',                          'Soupe au hamburger',                     '{"soups","chowders"}',
                '',
                '',
                '{}',
                'https://carlsbadcravings.com/wp-content/uploads/2019/04/hamburger-soup-13.jpg',
                'https://www.youtube.com/watch?v=cIfiIc0Syyg',
                '1. In a large saucepan, brown the beef (break up any lumps) along with the onion and garlic. Drain off excess fat and discard.
                2. Add potatoes, beef broth, tomatoes, tomato soup, Worcestershire sauce, salt, pepper, Italian spice and bay leaf. Bring to boil. Lower heat and simmer covered for about 10 – 15 minutes.
                3. Add the vegetables and continue simmering for about 15 – 20 minutes until the vegetables and potatoes are tender. Remove the bay leaf. Check seasoning and consistency, adjust as necessary. Add more broth or water if required.',
                40,                0,          0,
                '',
                0,              '',                 0),

               ('mm_pork',
                'Roasted Herbed Pork Loin',                'Longe de porc rôtie aux herbesr',        '{"main_meals","pork"}',
                '',
                '',
                '{}',
                'https://www.budgetbytes.com/wp-content/uploads/2012/02/Herb-Roasted-Pork-Tenderloin-sliced-500x500.jpg',
                'https://www.youtube.com/watch?v=o-7Cg1GYPSs',
                '1. Rub the vegetable oil all over the pork.
                2. Mix all of the spices together and rub all over the pork loin.
                3. Place the pork in a roasting pan or baking sheet. Cover with foil loosely to prevent the spices burning and place in a 325-f oven and bake until the internal temperature reaches 160 f to 165 f (for food safety, the use of a digital thermometer is key to ensuring that protein items are cooked to the correct temperature). Remove the foil for the last 15 to 20 minutes of cooking time.
                4. Remove from oven and let rest for about 15 minutes before slicing.',
                70,                0,          0,
                'Slice the pork thinly as thin slices taste better that thick slices. Serve with apple sauce.',
                0,              '',                 6),

               ('mm_pasta',
                'Macaroni and Cheese',                     'Macaroni au fromage',                    '{"main_meal", "pasta"}',
                '',
                '',
                '{}',
                'https://www.budgetbytes.com/wp-content/uploads/2021/12/Homemade-Mac-and-Cheese-fork.jpg',
                'https://www.youtube.com/watch?v=S-oDb94T1jk',
                'Preheat oven to 350f / 175c
                1.	Cook the noodles following package direction less 1-2 minutes, as the noodles will continue cooking in the sauce. Drain and rinse well under cold water.
                2.	For the sauce - In a large saucepan over medium heat, melt the butter. Add the flour and mix well. Lower heat and cook for about 5 minutes. Stir frequently.
                3.	Heat the milk in a separate pan until warm and slowly add to the butter/flour mixture (the roux) over low heat, stirring frequently, cook until sauce thickens slightly, about 10-15 minutes.
                4.	Remove from heat and add the cheese, salt and pepper. Stir until the cheese has melted. Place back on low heat if cheese does not fully melt.
                5.	Add the noodles to the sauce and mix well.Place in a greased 8" x 8" baking dish. If the sauce appears too thick, add some warmed milk until desired consistency is reached. Remember, sauce will thicken during cooking as the pasta will absorb the liquid.
                6.	Sprinkle the grated cheese, breadcrumbs and chili powder (optional) over the top and bake uncovered in pre-heated oven for about 20-25 minutes or until the sauce has bubbled around the edges and the top is nicely browned. Allow to sit for a few minutes before serving.',
                55,                0,          0,
                '',
                0,              '',                 4),

               ('main_beef',
                'Meatloaf',                                'Pain de viande',                         '{"main_meals","beef"}',
                '',
                '',
                '{}',
                'https://natashaskitchen.com/wp-content/uploads/2019/02/Meatloaf-Recipe.jpg',
                'https://www.youtube.com/watch?v=5Z3_crOr3hk',
                'Preheat the oven to 325f
                1. In a large bowl place the beef, bread crumbs, onion, milk, egg, BBQ sauce, Worcestershire sauce, parsley, salt, garlic powder and pepper. Using your hands, mix together until well combined.
                2. Add the meat mixture to a 9” x 5” loaf pan and lightly press down to level.
                3. In a small bowl add the ketchup, brown sugar and vinegar and stir to combine. Spread this sauce over the meatloaf evenly.
                4. Bake in a preheated oven for about 1 hour. Remove from the oven, Let the meatloaf rest for 10 minutes before removing from pan and slicing.',
                70,                0,          0,
                'For a complete meal, add mashed potatoes and a vegetable of your choice for a complete comforting meal.',
                0,              '',                 8),

               ('s_vegetable',
                'Mixed Bean salad',                        'Salade de haricots mélangés',            '{"salad","vegetable"}',
                'A simple and tasty salad, suitable to accompany almost any meal.',
                'Une salade simple et savoureuse, adaptée pour accompagner presque tous les repas.',
                '{}',
                'https://www.inspiredtaste.net/wp-content/uploads/2020/07/Bean-Salad-Recipe-1200.jpg',
                'https://www.youtube.com/watch?v=o6jf5k5MI5w',
                '1.	Combine the sugar, vinegar, oil and salt and pepper in a small saucepan. Cook over medium heat, whisking occasionally until the sugar is dissolved. Cool slightly.
                2. Combine the remaining ingredients in a glass bowl. Add the dressing and toss to coat.
                3. Cover and refrigerate overnight. Toss and serve using a slotted spoon. Serve over a crisp lettuce leaf.',
                20,                0,          0,
                '*Finely diced tomato can be substituted for the red pepper.',
                0,              '',                 8),

               ('mm_pork_side',
                'Oven baked Pork Chops with an onion, mushroom sauce','Côtelettes de porc cuites au four avec un oignon, sauce aux champignons','{"main_meal", "pork"}',
                '',
                '',
                '{}',
                'https://cafedelites.com/wp-content/uploads/2018/07/Seared-Pork-Chops-Creamy-Mushroom-IMAGE-2.jpg',
                'https://www.youtube.com/watch?v=qB3yeDOmgo4',
                'Pre-heat oven to 350f / 180c
                1.	Heat the oil over medium high heat in an oven safe, heavy bottomed skillet.
                2.	Sprinkle the pork chops with a little pepper and fry 2-3 minutes on each side until browned.
                3.	Sprinkle the chops with the onion soup mix and add the water to the skillet. Stir to mix.
                4.	Place the skillet in the pre-heated oven and bake for about 15- 20 minutes. After about 15 minutes add the sliced mushrooms to the skillet, mix and continue to bake for another 15 – 20 minutes until the pork chops are tender Remove the pork chops to a plate, reserving the drippings and mushrooms in the skillet.
                5.	To make the gravy - In a separate saucepan melt the butter or margarine over low heat. Stir in the flour and mix well together to make a roux. Cook until the roux is a light golden colour, stirring constantly. Continue to cook for a few minutes until the flour taste has been “cooked out”.
                6.	Spoon the roux into the skillet, turn heat to medium low and mix well with the drippings and mushrooms in the skillet. Add hot water if the sauce is too thick. Add the pork chops to the skillet and spoon over the gravy. Continue to cook for a few minutes until flavours have blended and chops and gravy have heated through. Taste for seasoning and adjust if necessary. Serve sprinkled with chopped parsley.',
                55,                0,          0,
                'Boneless chops may be used but do not generally have the flavour of bone in chops. Pork shoulder chops can be substituted for loin chops.',
                0,              '',                 4),

               ('sd_starches',
                'Rice Pilaf',                              'riz pilaf',                              '{"side_dish", "starches"}',
                '',
                '',
                '{}',
                'https://www.eazypeazymealz.com/wp-content/uploads/2018/12/rice-pilaf-6.jpg',
                'https://youtu.be/sYNI_xUwZ70',
                '1.	Heat the stock in saucepan. Meanwhile, in a large saucepan that has a well-fitting lid, add the oil and heat over medium heat. Add the onions, carrots and celery. Cook, stirring occasionally until the vegetables are just tender. Add the rice and, stirring, coat the rice with the oil.
                2. Add salt and pepper. Be careful not to add too much salt. Taste the broth and if salty, reduce the amount of added salt as the rice will absorb the salt.
                3. Add the hot broth to the rice. Most long grain rice requires 2 cups of liquid to every cup of rice. Stir while adding the broth. Bring to a boil. Reduce heat to very low, cover the saucepan and cook following rice package directions. Usually 15 – 25 minutes. Do not uncover the saucepan while the rice is cooking.
                4. After cooking for the appropriate time, remove from the heat and set aside, covered, for 10 minutes. Fluff the rice with a fork and stir in the chopped parsley.',
                35,                0,          0,
                '1. Try adding cooked green peas to the rice for an interesting variation
                2. Just Tender – The vegetables maintain a little firmness.',
                0,              '',                 8),

               ('sd_potatoes',
                'Roasted Potatoes',                        'Pommes de terre rôties',                 '{"side_dish", "potatoes", "vegetables"}',
                '',
                '',
                '{}',
                'https://www.howtocook.recipes/wp-content/uploads/2020/12/Roasted-potatoes-recipe.jpg',
                'https://youtu.be/kgTxgmX4It4',
                '1. Peel potatoes and wash well in cold water to remove some of the starch. Drain.
                2. Place the potatoes into a large saucepan, cover with cold water and add 1 Tsp. of salt. Bring to the boil, turn heat to medium and simmer until a small knife inserted into the potato meets a little resistance. Remove from the heat and cool slightly.
                3. Place the canola oil, the rosemary and ½ Tsp of salt and ¼ Tsp of pepper into a bowl. Add the potatoes and mix gently to coat the potatoes.
                4. Place the potatoes onto a baking sheet or into an ovenproof glass baking dish. Pour any remaining oil in the bowl over the potatoes and place in a 325-f oven and roast turning once, until a knife inserted into the potato meets no resistance and the potatoes are lightly browned and are crispy on the outside.',
                50,                0,          0,
                '',
                0,              '',                6),

               ('mm_chicken_side',
                'Sweet And Spicy Glazed Chicken Thighs',   'Cuisses De Poulet Glacées Sucrées Et Épicées', '{"main_meal", "chicken"}',
                '',
                '',
                '{}',
                'https://www.budgetbytes.com/wp-content/uploads/2018/09/Sweet-and-Spicy-Glazed-Chicken-Thighs-close-500x500.jpg',
                'https://www.youtube.com/watch?v=PLd2voZudMg',
                '1. In a small bowl combine the brown sugar, cayenne pepper, garlic powder, paprika, salt and pepper. Mix together.
                2. Using paper towels, pat dry the chicken thighs and liberally sprinkle the spice mixture over the chicken, coating both sides.
                3. Add the oil to a large skillet, frying pan or saucepan. Turn heat to medium low. When the oil is hot, add the chicken pieces and cook for approximately 5 – 7 minutes on each side until the chicken is cooked through and the sugar has turned into a deep brown glaze.
                Serve hot over rice or noodles. Add a vegetable of your choice for a complete meal.',
                25,                0,          0,
                '1. Remove the skin from the chicken prior to cooking.
                2. Be careful not to cook the chicken at too high a heat as this will burn the sugar.
                3. During cooking, move and turn the chicken pieces with a spatula to prevent sticking.',
                0,              '',                6),

               ('mm_beef_mix',
                'Beef Mix for Tacos',                      'Mélange de bœuf pour tacos',                   '{"main_meal", "beef"}',
                '',
                '',
                '{}',
                'https://www.countrysidecravings.com/wp-content/uploads/2018/04/homemade-ground-beef-taco-meat-picture-400x600.jpg',
                'https://www.youtube.com/watch?v=BDXV9FCPwEQ',
                '1. Place the oil in a heavy bottomed saucepan. Heat the oil over medium heat. When hot add the onion and fry until softened (do not brown)
                2. Add the ground beef and cook until cooked through and no pink remains. Drain and discard fat from the saucepan.
                3. Add the garlic, chili powder, cumin, coriander and the salt and pepper. Cook together for a few minutes.
                4. Add the tomato sauce and jalapenos. Lower heat and simmer until thickened. Taste for seasoning and adjust if necessary.
                5. Heat taco shells in oven until warm and crisp. Place 1 – 2 Tbsp. of meat mixture into shell and top with your favourite toppings - Shredded lettuce, diced tomato, onion, salsa, jalapenos and sour cream.',
                55,                0,          0,
                '',
                0,              '',                8),

               ('sauce',
                'Tartare Sauce',                           'sauce tartare',                                '{"sauce"}',
                'A classic accompaniment for battered fish',
                'Un accompagnement classique pour le poisson pané',
                '{}',
                'https://www.inspiredtaste.net/wp-content/uploads/2019/02/Homemade-Tartar-Sauce-Recipe-1-1200.jpg',
                'https://www.youtube.com/watch?v=kQhXXO_gC3k',
                'Place all of the ingredients in a bowl and mix together until thoroughly mixed. Cover and store in refrigerator for use.',
                15,                0,          0,
                '',
                0,              '',                0),

               ('sauce_side',
                'Tartare Sauce',                           'sauce tartare',                                '{"sauce"}',
                'A classic accompaniment for battered fish',
                'Un accompagnement classique pour le poisson pané',
                '{}',
                'https://www.inspiredtaste.net/wp-content/uploads/2019/02/Homemade-Tartar-Sauce-Recipe-1-1200.jpg',
                'https://www.youtube.com/watch?v=kQhXXO_gC3k',
                'Place all ingredients in a bowl and mix together until thoroughly mixed. Cover and store in refrigerator for use.',
                15,                0,          0,
                'Add 1 Tbsp. / 15ml of capers, mashed with a fork.',
                0,              '',                0),

               ('main_fish',
                'Tuna Noodle Casserole',                   'Casserole de nouilles au thon',                '{"main_meal", "fish"}',
                '',
                '',
                '{}',
                'https://www.howtocook.recipes/wp-content/uploads/2021/08/Tuna-casserole-recipe.jpg',
                'https://www.youtube.com/watch?v=eCRibnwPVgc',
                'Preheat oven to 325f
                1.	Cook noodles al dente, according to package directions. Drain, refresh (rinse well) and drain. Set aside covered in the refrigerator.
                2.	Melt the butter or margarine in a large saucepan. Add the onions and over medium heat, cook to soften (do not brown). Add the sliced mushrooms and cook for 3 – 4 minutes more.
                3.	Whisk together the milk and flour in a bowl, mixing well to remove any lumps. Slowly add to the mushroom, onion mixture, stirring well after each addition. Bring to a simmer and stir constantly until thickened. Cover with some greased parchment paper (to prevent skin forming). Lower the heat to very low and allow to sit for about 25 minutes, stirring occasionally, to cook out the taste of the flour.
                4.	Remove cover. Add some extra warm milk if sauce is too thick as the noodles will absorb some of the liquid and thicken the sauce while cooking. Stir and add the diced peppers, green peas, the thyme and salt and pepper to taste.
                5.	Add the noodles and stir gently to combine with the sauce. Place in a greased ovenproof baking dish, dot with butter or margarine and bake until heated through, lightly browned and bubbly.',
                60,                0,          0,
                '',
                0,              '',                6),

               ('salad_sandwiches',
                'Tuna Salad Sandwich',                     'Sandwich à la salade de thon',                 '{"sandwiches"}',
                '',
                '',
                '{}',
                'https://www.howtocook.recipes/wp-content/uploads/2021/08/Tuna-salad-recipe.jpg',
                'https://www.youtube.com/watch?v=k4debr24oBg',
                '1. Open the can of tuna and drain the liquid. Place tuna into a bowl.
                2. Break up the tuna using a fork. Add the mayonnaise and the salt and pepper and mix gently together.
                3. Lay out six (6) pieces of bread on a cutting board or counter top and divide and spread the filling between three (3) slices of bread. Top each with the remaining slices. Cut diagonally, wrap well and refrigerate for use.',
                20,                2.46,       0.82,
                '1. Try adding 1 ½ Tbsp. (22.5 ml) of finely chopped celery, green onion or onion to the tuna mixture. A pinch of dried dill weed adds an interesting twist.
                2. The number of sandwiches made will depend on the amount of filling placed on the bread.',
                0,              '',                3);

-- Products used in the meal recipes.
INSERT INTO
 app.product (name_en,              name_fr,                code,     price,    quantity,   unit,     upc,
              source_link,
              tags)
      VALUES ('Chicken Thighs',     'Cuisses de poulet',    'ct',     '13',     '650',      'g',      '62891582644',
              'https://www.walmart.ca/en/ip/prime-boneless-skinless-chicken-thighs-raised-without-antibiotics/6000201090600',
              '{"grocery", "chicken"}'),
             ('Vegetable Oil',      'Huile végétale',       'vo',     '9.27',   '2.84',     'L',      '62773501730',
              'https://www.walmart.ca/en/ip/great-value-vegetable-oil/6000202595279',
              '{"grocery","vegetable", "vegan"}'),
             ('Mayonnaise',         'Mayonnaise',           'mn',     '5.47',   '890',      'mL',     '6840066260',
              'https://www.walmart.ca/en/ip/hellmanns-real-mayonnaise/6000046528892',
              '{"grocery", "condiments", "spreads"}'),
             ('Salt',               'sel',                  'st',     '1.27',   '1',        'kg',     '6601000105',
              'https://www.walmart.ca/en/ip/windsor-table-salt/6000093210759',
              '{"condiments", "vegan", "vegetarian"}'),
             ('Pepper',             'poivre',               'pp',     '3.97',   '90',       'g',      '62891583143',
              'https://www.walmart.ca/en/ip/great-value-4-peppercorn-blend/6000199879504',
              '{"grocery", "pantry", "spices"}'),
             ('Bread',              'Pain',                 'bd',     '2.97',   '570',      'g',      '6034771116',
              'https://www.walmart.ca/en/ip/bens-holsum-fresh-100-whole-grain-wheat-bread/6000199144238',
              '{"grocery", "bakery", "bread"}'),

             ('Large Eggs',         'Gros oeufs',           'le',     '6.88',   '18',       'single', '77000414419',
              'https://www.walmart.ca/en/ip/maritime-pride-large-white-eggs/6000199065407',
              '{"grocery", "dairy", "eggs"}'),

             ('Dried Navy Beans',   'haricots blancs secs', 'dnb',    '3.37',   '900',      'g',      '62891536562',
              'https://www.walmart.ca/en/ip/great-value-navy-beans/6000196181063',
              '{"grocery", "pantry", "beans"}'),
             ('Onions',             'Oignons',              'oo',     '4.97',   '3',        'lb',     '3338360102',
              'https://www.walmart.ca/en/ip/onion-red/6000191282958',
              '{"grocery","vegetable", "onion"}'),
             ('Meaty Salt Pork',    'Porc salé à la viande','msp',    '7.97',   '375',      'g',      '6310037554',
              'https://www.walmart.ca/en/ip/maple-leaf-natural-less-salt-bacon/6000187092298',
              '{"grocery", "meat", "bacon"}'),
             ('Slices Of Bacon',    'tranches de bacon',    'sb',     '7.97',   '65',       'g',      '6310088800',
              'https://www.walmart.ca/en/ip/maple-leaf-ready-crisp-fully-cooked-natural-bacon-slices/6000187082624',
              '{"meat", "pork", "bacon"}'),
             ('Ketchup',            'Ketchup',              'ku',     '4.47',   '1',        'L',      '5700000299',
              'https://www.walmart.ca/en/ip/heinz-tomato-ketchup/6000001798466',
              '{"condiments", "vegan", "vegetarian"}'),
             ('Molasses',           'Mélasse',              'ms',     '3.27',   '675',      'g',      '68113191087',
              'https://www.walmart.ca/en/ip/great-value-100-pure-fancy-molasses/6000128603817',
              '{"pantry", "baking", "sugar"}'),
             ('Brown Sugar',        'Cassonade',            'bs',     '3.67',   '850',      'g',      '72636758456',
              'https://www.walmart.ca/en/ip/brown-cane-sugar/6000202815313',
              '{"pantry", "baking", "sugar"}'),
             ('Cider Vinegar',      'Vinaigre de cidre',    'cv',     '6.27',   '4',        'L',      '6401312029',
              'https://www.walmart.ca/en/ip/allens-apple-cider-vinegar/6000201177268',
              '{"pantry", "cooking", "vinegar"}'),
             ('Dry Mustard',        'Moutarde sèche',       'dm',     '3.97',   '55',       'g',      '400592470681',
              'https://www.walmart.ca/en/ip/plochmans-ground-mustard/6000199251954',
              '{"pantry", "spices"}'),

             ('Potatoes',           'Pommes de terre',      'pt',     '4.97',   '5',        'lb',     '60580600134',
              'https://www.walmart.ca/en/ip/potato-russet-your-fresh-market/6000196075654',
              '{"grocery", "vegetable", "vegan"}'),
             ('Butter',             'Beurre',               'bt',     '5.98',   '454',      'g',      '62891582939',
              'https://www.walmart.ca/en/ip/great-value-salted-butter/6000200237827',
              '{"grocery","dairy", "butter"}'),
             ('Broccoli',           'Brocoli',              'bc',     '3.97',   '12',       'oz',     '71651901301',
              'https://www.walmart.ca/en/ip/broccoli-florets-manns/6000195497402',
              '{"grocery", "vegan", "vegetarian"}'),
             ('Cheese Sauce',       'Sauce au fromage',     'cs',     '2.17',   '218',      'g',      '6563307540',
              'https://www.walmart.ca/en/ip/hamburger-helper-cheddar-cheese-melt/6000188959470',
              '{"pantry", "sides"}'),
             ('Grated Cheese',      'Fromage râpé',         'gc',     '6.97',   '250',      'g',      '6810000453',
              'https://www.walmart.ca/en/ip/kraft-grated-parmesan-cheese/19177',
              '{"pantry", "sides"}'),
             ('Bacon Bits',         'Lardons',              'bb',     '7.97',   '65',       'g',      '6310088800',
              'https://www.walmart.ca/en/ip/maple-leaf-ready-crisp-fully-cooked-natural-bacon-slices/6000187082624',
              '{"meat", "pork", "bacon"}'),
             ('Sour Cream',         'Crème aigre',          'sc',     '4.18',   '500',      'ml',     '6601314160',
              'https://www.walmart.ca/en/ip/gay-lea-foods-gay-lea-sour-cream-14-mf/6000191276913',
              '{"grocery", "dairy", "dips"}'),
             ('Green Onions',       'Oignons verts',        'go',     '1.27',   '1',        'bunch',  '3338360500',
              'https://www.walmart.ca/en/ip/green-onion/6000191275347',
              '{"grocery", "vegan", "vegetarian"}'),

             ('Flour',              'Farine',               'fl',     '5.97',   '2.5',      'kg',     '5900001658',
              'https://www.walmart.ca/en/ip/robin-hood-original-all-purpose-flour-25kg/6000016955603',
              '{"pantry", "baking", "flour"}'),
             ('Baking Powder',      'Levure chimique',      'bp',     '5.97',   '650',      'g',      '5833601130',
              'https://www.walmart.ca/en/ip/dr-oetker-baking-powder/6000202673901',
              '{"pantry", "baking"}'),
             ('Buttermilk',         'Babeurre',             'bm',     '2.48',   '1',        'L',      '6047766111',
              'https://www.walmart.ca/en/ip/northumberland-buttermilk/6000200647779',
              '{"grocery", "dairy", "milk"}'),
             ('Soda Water',         'Eau gazifiée',         'sw',     '1',      '1',        'L',      '62891556178',
              'https://www.walmart.ca/en/ip/our-finest-natural-spring-water-carbonated/6000197437995',
              '{"grocery", "drinks"}'),
             ('Haddock Fish',       'Poisson Haddock',      'hf',     '12.97',  '580',      'g',      '6176309034',
              'https://www.walmart.ca/en/ip/catch-of-the-day-haddock-fillets/6000198998193',
              '{"grocery", "seafood"}'),

             ('Stewing beef',       'Boeuf à bouillir',     'sb',     '12.86',  '650',      'g',      '22047000000',
              'https://www.walmart.ca/en/ip/aaa-angus-halal-beef-stewing-cubes-your-fresh-market/6000199409079',
              '{"grocery", "meat"}'),
             ('Celery Sticks',      'Bâtonnets de céleri',  'cs',     '3.77',   '200',      'g',      '7315015201',
              'https://www.walmart.ca/en/ip/celery-sticks/6000196078868',
              '{"grocery", "vegetable"}'),
             ('Carrot',             'Carotte',              'cr',     '3.47',   '3',        'lb',     '3338366002',
              'https://www.walmart.ca/en/ip/carrot-your-fresh-market/6000197111434',
              '{"grocery", "vegetables"}'),
             ('Garlic',             'Ail',                  'gl',     '0.78',   '3',        'pack',   '67929500051',
              'https://www.walmart.ca/en/ip/garlic/6000191273738',
              '{"grocery", "garlic"}'),
             ('Tomato Paste',       'Pâte De Tomate',       'tp',     '1.17',   '156',      'ml',     '5880738813',
              'https://www.walmart.ca/en/ip/hunts-original-tomato-paste/6000016953441',
              '{"grocery", "pantry", "canned"}'),
             ('Beef Broth',         'Bouillon de boeuf',    'bb',     '1.97',   '900',      'ml',     '6321114358',
              'https://www.walmart.ca/en/ip/campbells-beef-broth/6000016939279',
              '{"grocery", "pantry", "soup"}'),
             ('Water',              'leau',                 'wt',     '1.48',   '4',        'L',      '60538892849',
              'https://www.walmart.ca/en/ip/great-value-4l-natural-spring-water/6000143709812',
              '{"grocery", "water"}'),
             ('Bay Leaf',           'Feuille de laurier',   'bl',     '1.97',   '15',       'g',      '68113186223',
              'https://www.walmart.ca/en/ip/great-value-bay-leaves-herb/6000152266364',
              '{"grocery", "herb"}'),
             ('Thyme',              'Thym',                 'ty',     '1.97',   '50',       'g',      '68113186253',
              'https://www.walmart.ca/en/ip/great-value-club-house-thyme-leaves/6000153707024',
              '{"pantry", "herb", "spices"}'),

             ('Macaroni Noodles',   'Nouilles macaronis',   'mn',     '1.27',   '900',      'g',      '60538888129',
              'https://www.walmart.ca/en/ip/great-value-dry-macaroni/6000001842787',
              '{"pantry", "pasta"}'),
             ('Ground Beef',        'Le bœuf haché',        'gb',     '5.47',   '454',      'g',      '62891582518',
              'https://www.walmart.ca/en/ip/ground-beef-regular-tube-your-fresh-market/6000199127363',
              '{"grocery", "meat"}'),
             ('Diced Tomatoes',     'Tomates en dés',       'dt',     '1.97',   '796',      'ml',     '5880766561',
              'https://www.walmart.ca/en/ip/aylmer-tomatoes-diced/6000200290283',
              '{"pantry", "canned"}'),
             ('Dried Basil',        'Basilic séché',        'db',     '1.97',   '50',       'g',      '68113186222',
              'https://www.walmart.ca/en/ip/great-value-basil-leaves-herb/6000152266020',
              '{"grocery", "herb", "italian"}'),
             ('Dried Oregano',      'Origan séché',         'do',     '2.97',   '72',       'g',      '60538888113',
              'https://www.walmart.ca/en/ip/great-value-oregano-leaves/6000148921170',
              '{"grocery", "pantry", "herbs", "spices"}'),

             ('Raisins',            'Raisins secs',         'rs',     '6.97',   '750',      'g',      '62891540901',
              'https://www.walmart.ca/en/ip/great-value-seedless-thompson-raisins/6000196889060',
              '{"pantry", "baking"}'),
             ('Sugar',              'Du sucre',             'sg',     '2.77',   '2',        'kg',     '6284721023',
              'https://www.walmart.ca/en/ip/redpath-special-fine-granulated-sugar/6000023803963',
              '{"pantry", "baking"}'),
             ('Milk',               'Du lait',              'ml',     '4.09',   '2',        'L',      '6047722102',
              'https://www.walmart.ca/en/ip/northumberland-homogenized-325-milk/6000199063915',
              '{"grocery", "dairy", "milk"}'),
             ('Ground Nutmeg',      'Muscade moulue',       'gn',     '1.97',   '80',       'g',      '62891566941',
              'https://www.walmart.ca/en/ip/great-value-ground-nutmeg/6000197916927',
              '{"grocery", "pantry"}'),
             ('Ground Cinnamon',    'Cannelle moulue',      'gc',     '1.97',   '125',      'g',      '62891536202',
              'https://www.walmart.ca/en/ip/great-value-ground-cinnamon/6000196207716',
              '{"pantry", "spices", "herbs"}'),
             ('Apricot Jam',        'Confiture dabricot',   'aj',     '2.97',   '500',      'ml',     '6481932740',
              'https://www.walmart.ca/en/ip/light-apricot-spread-500ml/6000203945595',
              '{"pantry", "spreads"}'),

             ('English Muffin',     'Muffin anglais',       'em',     '3.17',   '340',      'g',      '6034724277',
              'https://www.walmart.ca/en/ip/bens-white-english-muffins/6000201919526',
              '{"grocery", "bakery"}'),
             ('Cheddar Cheese',     'Fromage cheddar',      'cc',     '5.98',   '400',      'g',      '62773501449',
              'https://www.walmart.ca/en/ip/great-value-old-cheddar-cheese/6000201734274',
              '{"grocery", "dairy"}'),

             ('Chicken Breasts',    'Poitrines de poulet',  'cb',     '12',     '1',        'kg',     '60538876501',
              'https://www.walmart.ca/en/ip/boneless-skinless-chicken-breasts/6000191279307',
              '{"pantry", "meat"}'),
             ('Pepper',             'Poivre',               'pp',     '1.56',   '0.24',     'kg',     '4065',
              'https://www.walmart.ca/en/ip/pepper-green-bell/6000191286438',
              '{"grocery", "vegetable"}'),
             ('Taco Spice Mix',     'Mélange dépices pour tacos', 'tsm','1',    '35',       'g',      '60538887436',
              'https://www.walmart.ca/en/ip/great-value-taco-seasoning-mix/6000149160590',
              '{"grocery", "pantry", "spices"}'),
             ('Tortilla Wraps',     'Wraps de tortillas',   'tw',     '4.37',   '610',      'g',      '6872103811',
              'https://www.walmart.ca/en/ip/dempsters-original-large-tortillas/1062614',
              '{"grocery", "bakery"}'),
             ('Salsa',              'Salsa',                'sl',     '3.37',   '650',      'ml',     '68113171310',
              'https://www.walmart.ca/en/ip/great-value-thickn-chunky-mild-salsa/6000082735874',
              '{"grocery", "mexican"}'),

             ('Fresh Parsley',      'Persil frais',         'fp',     '1.97',   '1',        'bunch',  '20490100000',
              'https://www.walmart.ca/en/ip/parsley-flat-fresh/6000191272067',
              '{"grocery", "fresh"}'),
             ('Bread Crumbs',       'Chapelure',            'bc',     '2.97',   '425',      'g',      '62891516502',
              'https://www.walmart.ca/en/ip/great-value-plain-bread-crumbs/6000196037756',
              '{"pantry", "coatings"}'),

             ('Tomato Soup',        'Soupe à la tomate',    'ts',     '1.27',   '284',      'ml',     '6321100011',
              'https://www.walmart.ca/en/ip/campbells-tomato-condensed-soup/6000016942445',
              '{"pantry", "canned"}'),
             ('Worcestershire Sauce', 'Sauce Worcestershire', 'ws',   '2.97',   '142',      'ml',     '5700000913',
              'https://www.walmart.ca/en/ip/lea-perrins-worchestershire-sauce/6000148205475',
              '{"pantry", "sauces"}'),
             ('Italian spice',      'Épice italienne',      'is',     '1.97',   '50',       'g',      '68113186237',
              'https://www.walmart.ca/en/ip/great-value-italian-seasoning/6000152506491',
              '{"pantry", "spices"}'),
             ('Mixed Vegetables',   'Légumes mélangés',     'mv',     '1.98',   '750',      'g',      '62891508540',
              'https://www.walmart.ca/en/ip/great-value-frozen-mixed-vegetables/6000191274026',
              '{"grocery", "vegetable", "vegan"}'),

             ('Boneless Pork Loin', 'Longe de porc désossée', 'bpl',  '14.80',  '1.3',      'kg',     '22102700000',
              'https://www.walmart.ca/en/ip/maple-leaf-fresh-boneless-pork-shoulder-roast/6000196382841',
              '{"grocery", "meat", "fresh"}'),
             ('Dried Rosemary',     'Romarin séché',        'dr',     '1.97',   '50',       'g',      '68113186250',
              'https://www.walmart.ca/en/ip/great-value-rosemary-leaves/6000153706611',
              '{"grocery", "herbs", "spices"}'),
             ('Garlic Powder',      'Poudre dail',          'gp',     '1.97',   '150',      'g',      '68113186234',
              'https://www.walmart.ca/en/ip/great-value-garlic-powder/6000153706882',
              '{"pantry", "herbs", "spices"}'),

             ('Chili Powder',       'Poudre de chili',      'cp',     '1.97',   '150',      'g',      '68113186229',
              'https://www.walmart.ca/en/ip/great-value-chili-powder-seasoning/6000152266516',
              '{"pantry", "cooking"}'),

             ('BBQ sauce',          'Sauce barbecue',       'bs',     '0.77',   '455',      'ml',     '6810007852',
              'https://www.walmart.ca/en/ip/kraft-bbq-sauce-original/6000016939704',
              '{"grocery", "condiments", "sauces"}'),

             ('Canola Oil',         'Huile de canola',      'co',     '8.97',   '2.84',     'L',      '62773501731',
              'https://www.walmart.ca/en/ip/great-value-canola-oil/6000202595784',
              '{"grocery","vegetable", "onion"}'),
             ('White Navy Beans',   'Haricots blancs blancs', 'wnb',  '1.17',   '540',      'ml',     '68113186152',
              'https://www.walmart.ca/en/ip/great-value-navy-beans/6000127514355',
              '{"grocery", "canned"}'),
             ('Cut Wax Beans',      'Couper les haricots jaunes', 'cwb', '1.97', '398',     'ml',     '19056916660',
              'https://www.walmart.ca/en/ip/our-vegetables-are-picked-at-the-peak-of-perfection-and-conveniently-packed-so-you-can-have-the-fresh-taste-of-green-giant-vegetables-year-round/6000196898313',
              '{"grocery", "pantry", "canned"}'),
             ('Cut Green Beans',    'Couper les haricots verts', 'cgb', '1.97',  '398',     'ml',     '19056916160',
              'https://www.walmart.ca/en/ip/green-giant-canned-cut-green-beans/6000196898307',
              '{"grocery", "pantry", "canned"}'),
             ('Red Pepper',         'Poivron rouge',        'rp',     '2.34',   '200',      'g',      '20472200000',
              'https://www.walmart.ca/en/ip/pepper-red-bell/6000195506337',
              '{"grocery", "fresh", "vegetable"}'),
             ('Lettuce',            'Salade',               'lt',     '1.97',   '1',        'ea',   '33383651415',
              'https://www.walmart.ca/en/ip/lettuce-green-leaf/6000196006949',
              '{"grocery", "fresh", "vegetable"}'),

             ('Pork Chops',         'Côtes de porc',        'pc',     '7.90',   '600',      'g',      '22132600000',
              'https://www.walmart.ca/en/ip/greenfield-pork-loin-boneless-chops-raised-without-antibiotics/6000200253274',
              '{"grocery", "meat", "fresh"}'),
             ('Onion Soup Mix',     'Mélange pour soupe à loignon', 'osm', '1.97', '113',   'g',      '62891567011',
              'https://www.walmart.ca/en/ip/great-value-onion-soup-and-recipe-mix/6000200127717',
              '{"grocery", "pantry", "soup"}'),
             ('Mushroom',           'Champignon',           'mr',     '2.47',   '8',        'oz',     '3338345080',
              'https://www.walmart.ca/en/ip/mushrooms-whole-white-your-fresh-market/6000196142665',
              '{"grocery", "meal"}'),

             ('White Rice',         'Riz blanc',            'wr',     '3.97',   '900',      'g',      '62773502064',
              'https://www.walmart.ca/en/ip/great-value-basmati-rice/6000203077608',
              '{"grocery", "indian cuisine"}'),
             ('Chicken Broth',      'Bouillon de poulet',   'cb',     '2.17',   '946',      'ml',     '62891523568',
              'https://www.walmart.ca/en/ip/great-value-organic-chicken-broth/6000194789807',
              '{"grocery", "pantry", "soups"}'),

             ('Cayenne Pepper',     'Poivre de Cayenne',    'cp',     '1.97',   '125',      'g',      '68113186226',
              'https://www.walmart.ca/en/ip/great-value-cayenne-pepper-spice/6000152266119',
              '{"grocery","spices"}'),
             ('Paprika',            'Paprika',              'pr',     '1.97',   '130',      'g',      '68113186244',
              'https://www.walmart.ca/en/ip/great-value-paprika-spice/6000153706263',
              '{"grocery", "spices"}'),
             
             ('Ground Cumin',       'Cumin en poudre',      'gc',     '1.97',   '97',       'g',      '62891566939',
              'https://www.walmart.ca/en/ip/great-value-ground-cumin/6000197918304',
              '{"grocery", "spices"}'),
             ('Ground Coriander',   'Coriandre moulue',     'gc',     '1.17',   '40',       'g',      '6946791708',
              'https://www.walmart.ca/en/ip/amira-coriander-ground/6000196236817',
              '{"grocery", "indian-cuisine", "spices"}'),
             ('Tomato Sauce',       'Sauce tomate',         'ts',     '1.47',   '680',      'ml',     '68113175984',
              'https://www.walmart.ca/en/ip/great-value-tomato-sauce/6000153706477',
              '{"grocery", "pantry", "canned"}'),
             ('Jalapeno Pepper',    'Piment jalapeno',      'jp',     '4.97',   '9',        'oz',     '67929500217',
              'https://www.walmart.ca/en/ip/pepper-jalapeno/6000196099498',
              '{"grocery", "vegetable", "vegan"}'),
             ('Taco Shells',        'Coquilles à tacos',    'ts',     '3.47',   '133',      'g',      '5830019684',
              'https://www.walmart.ca/en/ip/old-el-paso-gluten-free-stand-n-stuff-taco-shells/6000021060758',
              '{"grocery", "gluten-free", "instant"}'),

             ('Sweet Relish',       'Confiture sucrée',     'sr',     '3.77',   '500',      'ml',     '5900000342',
              'https://www.walmart.ca/en/ip/bicks-squeeze-sweet-green-relish/6000016949463',
              '{"grocery", "pantry", "condiments"}'),
             ('Yellow Mustard',     'Moutarde jaune',       'ym',     '1.97',   '400',      'ml',     '5620076217',
              'https://www.walmart.ca/en/ip/frenchs-classic-yellow-mustard-400ml/6000083048258',
              '{"grocery","pantry", "condiments"}'),
             ('Lemon',              'Citron',               'lm',     '.97',    '1',        'single', '20495800000',
              'https://www.walmart.ca/en/ip/lemon/6000191268545',
              '{"condiments", "vegetable"}'),

             ('Dill Pickles',       'Cornichons à laneth',  'dp',     '2.47',   '500',      'ml',     '62891582830',
              'https://www.walmart.ca/en/ip/great-value-tangy-dill-sandwich-pickles/6000200218292',
              '{"grocery", "pantry", "condiments"}'),

             ('Egg Noodles',        'Nouilles aux oeufs',   'en',     '2.27',   '340',      'g',      '6420013044',
              'https://www.walmart.ca/en/ip/no-yolks-broad-egg-white-noodles-pasta/PRD5NGQJJHP4FJH',
              '{"grocery", "pantry", "pasta"}'),
             ('Tuna',               'Thon',                 'tn',     '1.67',   '170',      'g',      '6136243430',
              'https://www.walmart.ca/en/ip/clover-leaf-flaked-light-tuna-skipjack-in-water/6000074943818',
              '{"grocery", "canned"}'),
             ('Green Peas',         'Pois verts',           'gp',     '1.98',   '750',      'g',      '62891575178',
              'https://www.walmart.ca/en/ip/great-value-grade-a-green-peas/6000198512913',
              '{"grocery", "frozen"}'),
             ('White Pepper',       'Poivre blanc',         'wp',     '5.97',   '47',       'g',      '6620000429',
              'https://www.walmart.ca/en/ip/mccormick-gourmet-ground-white-pepper-47g/6000041103757',
              '{"grocery", "pantry", "spices"}');

-- Ingredients used in the meal recipes.
INSERT INTO
      app.measure(unit,       quantity, product_id,                                      meal_id)
          VALUES ('oz',       6,        app_private.product_id_by_upc('62891582644'),    app_private.meal_id_by_code('c_sandwiches')),
                 ('tsp',      1,        app_private.product_id_by_upc('62773501730'),    app_private.meal_id_by_code('c_sandwiches')),
                 ('tbsp',     3,        app_private.product_id_by_upc('6840066260'),     app_private.meal_id_by_code('c_sandwiches')),
                 ('pinch',    0,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('c_sandwiches')),
                 ('pinch',    0,        app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('c_sandwiches')),
                 ('slice',    0,        app_private.product_id_by_upc('6034771116'),     app_private.meal_id_by_code('c_sandwiches')),

                 ('ea',       2,        app_private.product_id_by_upc('77000414419'),    app_private.meal_id_by_code('e_sandwiches')),
                 ('tbsp',     2,        app_private.product_id_by_upc('6840066260'),     app_private.meal_id_by_code('e_sandwiches')),
                 ('pinch',    0,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('e_sandwiches')),
                 ('pinch',    0,        app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('e_sandwiches')),
                 ('slice',    6,        app_private.product_id_by_upc('6034771116'),     app_private.meal_id_by_code('e_sandwiches')),

                 ('cup',      4,        app_private.product_id_by_upc('62891536562'),    app_private.meal_id_by_code('mm_baked_beans')),
                 ('ea',       3,        app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('mm_baked_beans')),
                 ('g',        227,      app_private.product_id_by_upc('6310037554'),     app_private.meal_id_by_code('mm_baked_beans')),
                 ('ea',       5,        app_private.product_id_by_upc('6310088800'),     app_private.meal_id_by_code('mm_baked_beans')),
                 ('cup',      1,        app_private.product_id_by_upc('5700000299'),     app_private.meal_id_by_code('mm_baked_beans')),
                 ('ml',       125,      app_private.product_id_by_upc('68113191087'),    app_private.meal_id_by_code('mm_baked_beans')),
                 ('ml',       63,       app_private.product_id_by_upc('72636758456'),    app_private.meal_id_by_code('mm_baked_beans')),
                 ('tbsp',     2,        app_private.product_id_by_upc('6401312029'),     app_private.meal_id_by_code('mm_baked_beans')),
                 ('tbsp',     1,        app_private.product_id_by_upc('400592470681'),   app_private.meal_id_by_code('mm_baked_beans')),
                 ('pinch',    0,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('mm_baked_beans')),
                 ('pinch',    0,        app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('mm_baked_beans')),

                 ('ea',       4,        app_private.product_id_by_upc('60580600134'),    app_private.meal_id_by_code('s_starches')),
                 ('pinch',    0,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('s_starches')),
                 ('tbsp',     1,        app_private.product_id_by_upc('62891582939'),    app_private.meal_id_by_code('s_starches')),
                 ('piece',    10,       app_private.product_id_by_upc('71651901301'),    app_private.meal_id_by_code('s_starches')),
                 ('tbsp',     2,        app_private.product_id_by_upc('6563307540'),     app_private.meal_id_by_code('s_starches')),
                 ('tbsp',     2,        app_private.product_id_by_upc('6810000453'),     app_private.meal_id_by_code('s_starches')),
                 ('bits',     10,       app_private.product_id_by_upc('6310088800'),     app_private.meal_id_by_code('s_starches')),
                 ('tbsp',     1,        app_private.product_id_by_upc('6601314160'),     app_private.meal_id_by_code('s_starches')),
                 ('bunch',    1,        app_private.product_id_by_upc('3338360500'),     app_private.meal_id_by_code('s_starches')),
                
                 ('cup',      1.25,     app_private.product_id_by_upc('5900001658'),     app_private.meal_id_by_code('mm_fish')),
                 ('tsp',      1.75,     app_private.product_id_by_upc('5833601130'),     app_private.meal_id_by_code('mm_fish')),
                 ('pinch',    0,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('mm_fish')),
                 ('pinch',    0,        app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('mm_fish')),
                 ('ml',       250,      app_private.product_id_by_upc('6047766111'),     app_private.meal_id_by_code('mm_fish')),
                 ('splash',   0,        app_private.product_id_by_upc('62891556178'),    app_private.meal_id_by_code('mm_fish')),
                 ('cup',      0.5,      app_private.product_id_by_upc('5900001658'),     app_private.meal_id_by_code('mm_fish')),
                 ('lb',       1,        app_private.product_id_by_upc('6176309034'),     app_private.meal_id_by_code('mm_fish')),
                 ('cup',      6,        app_private.product_id_by_upc('62773501730'),    app_private.meal_id_by_code('mm_fish')),
                
                 ('ml',       60,       app_private.product_id_by_upc('5900001658'),     app_private.meal_id_by_code('mm_beef')),
                 ('kg',       1.14,     app_private.product_id_by_upc('22047000000'),    app_private.meal_id_by_code('mm_beef')),
                 ('tbsp',     3,        app_private.product_id_by_upc('62773501730'),    app_private.meal_id_by_code('mm_beef')),
                 ('tbsp',     2,        app_private.product_id_by_upc('6401312029'),     app_private.meal_id_by_code('mm_beef')),
                 ('ea',       1,        app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('mm_beef')),
                 ('ea',       3,        app_private.product_id_by_upc('7315015201'),     app_private.meal_id_by_code('mm_beef')),
                 ('ea',       3,        app_private.product_id_by_upc('3338366002'),     app_private.meal_id_by_code('mm_beef')),
                 ('ea',       3,        app_private.product_id_by_upc('67929500051'),    app_private.meal_id_by_code('mm_beef')),
                 ('ml',       23,       app_private.product_id_by_upc('5880738813'),     app_private.meal_id_by_code('mm_beef')),
                 ('cup',      4,        app_private.product_id_by_upc('6321114358'),     app_private.meal_id_by_code('mm_beef')),
                 ('cup',      2,        app_private.product_id_by_upc('60538892849'),    app_private.meal_id_by_code('mm_beef')),
                 ('ea',       1,        app_private.product_id_by_upc('68113186223'),    app_private.meal_id_by_code('mm_beef')),
                 ('tsp',      0.5,      app_private.product_id_by_upc('68113186253'),    app_private.meal_id_by_code('mm_beef')),
                 ('pinch',    0,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('mm_beef')),
                 ('pinch',    0,        app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('mm_beef')),
                 ('lb',       1,        app_private.product_id_by_upc('60580600134'),    app_private.meal_id_by_code('mm_beef')),
                
                 ('lb',       1,        app_private.product_id_by_upc('60538888129'),    app_private.meal_id_by_code('mm_beef_side')),
                 ('kg',       1.14,     app_private.product_id_by_upc('62891582518'),    app_private.meal_id_by_code('mm_beef_side')),
                 ('g',        227,      app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('mm_beef_side')),
                 ('g',        114,      app_private.product_id_by_upc('4065'),           app_private.meal_id_by_code('mm_beef_side')),
                 ('ea',       4,        app_private.product_id_by_upc('67929500051'),    app_private.meal_id_by_code('mm_beef_side')),
                 ('ml',       796,      app_private.product_id_by_upc('5880766561'),     app_private.meal_id_by_code('mm_beef_side')),
                 ('oz',       6,        app_private.product_id_by_upc('5880738813'),     app_private.meal_id_by_code('mm_beef_side')),
                 ('ml',       15,       app_private.product_id_by_upc('6401312029'),     app_private.meal_id_by_code('mm_beef_side')),
                 ('ml',       10,       app_private.product_id_by_upc('68113186222'),    app_private.meal_id_by_code('mm_beef_side')),
                 ('ml',       10,       app_private.product_id_by_upc('60538888113'),    app_private.meal_id_by_code('mm_beef_side')),
                 ('tsp',      1.5,      app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('mm_beef_side')),
                 ('tsp',      0.5,      app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('mm_beef_side')),
                
                 ('slice',    10,       app_private.product_id_by_upc('6034771116'),     app_private.meal_id_by_code('desserts')),
                 ('ml',       60,       app_private.product_id_by_upc('62891582939'),    app_private.meal_id_by_code('desserts')),
                 ('ml',       250,      app_private.product_id_by_upc('62891540901'),    app_private.meal_id_by_code('desserts')),
                 ('ml',       45,       app_private.product_id_by_upc('6284721023'),     app_private.meal_id_by_code('desserts')),
                 ('ea',       5,        app_private.product_id_by_upc('77000414419'),    app_private.meal_id_by_code('desserts')),
                 ('ml',       625,      app_private.product_id_by_upc('6047722102'),     app_private.meal_id_by_code('desserts')),
                 ('tsp',      0.25,     app_private.product_id_by_upc('62891566941'),    app_private.meal_id_by_code('desserts')),
                 ('ml',       1.5,      app_private.product_id_by_upc('62891536202'),    app_private.meal_id_by_code('desserts')),
                 ('ml',       125,      app_private.product_id_by_upc('6481932740'),     app_private.meal_id_by_code('desserts')),
                
                 ('ea',       1,        app_private.product_id_by_upc('6034724277'),     app_private.meal_id_by_code('breakfast')),
                 ('slice',    1,        app_private.product_id_by_upc('6310088800'),     app_private.meal_id_by_code('breakfast')),
                 ('ea',       1,        app_private.product_id_by_upc('77000414419'),    app_private.meal_id_by_code('breakfast')),
                 ('slice',    1,        app_private.product_id_by_upc('62773501449'),    app_private.meal_id_by_code('breakfast')),
                 ('little',   0,        app_private.product_id_by_upc('62891582939'),    app_private.meal_id_by_code('breakfast')),
                 ('pinch',    0,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('breakfast')),
                 ('pinch',    0,        app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('breakfast')),
                
                 ('lb',       1.5,      app_private.product_id_by_upc('60538876501'),    app_private.meal_id_by_code('mm_chicken')),
                 ('tbsp',     2,        app_private.product_id_by_upc('62773501730'),    app_private.meal_id_by_code('mm_chicken')),
                 ('ea',       1,        app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('mm_chicken')),
                 ('ea',       1.5,      app_private.product_id_by_upc('4065'),           app_private.meal_id_by_code('mm_chicken')),
                 ('pkg',      0.5,      app_private.product_id_by_upc('60538887436'),    app_private.meal_id_by_code('mm_chicken')),
                 ('tsp',      0.5,      app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('mm_chicken')),
                 ('tsp',      0.25,     app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('mm_chicken')),
                 ('ea',       6,        app_private.product_id_by_upc('6872103811'),     app_private.meal_id_by_code('mm_chicken')),
                 ('g',        170,      app_private.product_id_by_upc('62773501449'),    app_private.meal_id_by_code('mm_chicken')),
                 ('tbsp',     6,        app_private.product_id_by_upc('6601314160'),     app_private.meal_id_by_code('mm_chicken')),
                 ('tbsp',     6,        app_private.product_id_by_upc('68113171310'),    app_private.meal_id_by_code('mm_chicken')),
                
                 ('ea',       4,        app_private.product_id_by_upc('60580600134'),    app_private.meal_id_by_code('mm_fish_side')),
                 ('lb',       2,        app_private.product_id_by_upc('6176309034'),     app_private.meal_id_by_code('mm_fish_side')),
                 ('ea',       1,        app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('mm_fish_side')),
                 ('ea',       2,        app_private.product_id_by_upc('77000414419'),    app_private.meal_id_by_code('mm_fish_side')),
                 ('tbsp',     6,        app_private.product_id_by_upc('20490100000'),    app_private.meal_id_by_code('mm_fish_side')),
                 ('tsp',      1,        app_private.product_id_by_upc('400592470681'),   app_private.meal_id_by_code('mm_fish_side')),
                 ('ml',       90,       app_private.product_id_by_upc('6601314160'),     app_private.meal_id_by_code('mm_fish_side')),
                 ('tsp',      2,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('mm_fish_side')),
                 ('tsp',      0.5,      app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('mm_fish_side')),
                 ('g',        200,      app_private.product_id_by_upc('62891516502'),    app_private.meal_id_by_code('mm_fish_side')),
                 ('L',        1,        app_private.product_id_by_upc('62773501730'),    app_private.meal_id_by_code('mm_fish_side')),
                
                 ('ea',       4,        app_private.product_id_by_upc('60580600134'),    app_private.meal_id_by_code('s_starches_side')),
                 ('ea',       3,        app_private.product_id_by_upc('67929500051'),    app_private.meal_id_by_code('s_starches_side')),
                 ('ml',       60,       app_private.product_id_by_upc('62891582939'),    app_private.meal_id_by_code('s_starches_side')),
                 ('ml',       63,       app_private.product_id_by_upc('6047722102'),     app_private.meal_id_by_code('s_starches_side')),
                 ('tsp',      1,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('s_starches_side')),
                 ('pinch',    0,        app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('s_starches_side')),
                
                 ('lb',       1,        app_private.product_id_by_upc('62891582518'),    app_private.meal_id_by_code('s_chowders')),
                 ('ea',       1,        app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('s_chowders')),
                 ('ea',       2,        app_private.product_id_by_upc('67929500051'),    app_private.meal_id_by_code('s_chowders')),
                 ('ea',       2,        app_private.product_id_by_upc('60580600134'),    app_private.meal_id_by_code('s_chowders')),
                 ('cup',      4,        app_private.product_id_by_upc('6321114358'),     app_private.meal_id_by_code('s_chowders')),
                 ('oz',       28,       app_private.product_id_by_upc('5880766561'),     app_private.meal_id_by_code('s_chowders')),
                 ('oz',       10,       app_private.product_id_by_upc('6321100011'),     app_private.meal_id_by_code('s_chowders')),
                 ('ml',       10,       app_private.product_id_by_upc('5700000913'),     app_private.meal_id_by_code('s_chowders')),
                 ('ml',       5,        app_private.product_id_by_upc('68113186237'),    app_private.meal_id_by_code('s_chowders')),
                 ('ea',       1,        app_private.product_id_by_upc('68113186223'),    app_private.meal_id_by_code('s_chowders')),
                 ('cup',      3,        app_private.product_id_by_upc('62891508540'),    app_private.meal_id_by_code('s_chowders')),
                 ('pinch',    0,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('s_chowders')),
                 ('pinch',    0,        app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('s_chowders')),
                
                 ('lb',       2.5,      app_private.product_id_by_upc('22102700000'),    app_private.meal_id_by_code('mm_pork')),
                 ('tbsp',     2,        app_private.product_id_by_upc('62773501730'),    app_private.meal_id_by_code('mm_pork')),
                 ('ml',       5,        app_private.product_id_by_upc('68113186250'),    app_private.meal_id_by_code('mm_pork')),
                 ('ml',       2.5,      app_private.product_id_by_upc('68113186253'),    app_private.meal_id_by_code('mm_pork')),
                 ('tsp',      1,        app_private.product_id_by_upc('68113186234'),    app_private.meal_id_by_code('mm_pork')),
                 ('tsp',      0.5,      app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('mm_pork')),
                 ('tsp',      0.25,     app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('mm_pork')),
                
                 ('lb',       0.5,      app_private.product_id_by_upc('60538888129'),    app_private.meal_id_by_code('mm_pasta')),
                 ('ml',       60,       app_private.product_id_by_upc('62891582939'),    app_private.meal_id_by_code('mm_pasta')),
                 ('ml',       83,       app_private.product_id_by_upc('5900001658'),     app_private.meal_id_by_code('mm_pasta')),
                 ('ml',       750,      app_private.product_id_by_upc('6047722102'),     app_private.meal_id_by_code('mm_pasta')),
                 ('g',        284,      app_private.product_id_by_upc('62773501449'),    app_private.meal_id_by_code('mm_pasta')),
                 ('tsp',      0.5,      app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('mm_pasta')),
                 ('pinch',    0,        app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('mm_pasta')),
                 ('tbsp',     1,        app_private.product_id_by_upc('62773501449'),    app_private.meal_id_by_code('mm_pasta')),
                 ('tbsp',     1,        app_private.product_id_by_upc('62891516502'),    app_private.meal_id_by_code('mm_pasta')),
                 ('pinch',    0,        app_private.product_id_by_upc('68113186229'),    app_private.meal_id_by_code('mm_pasta')),
                
                 ('lb',       2.5,      app_private.product_id_by_upc('62891582518'),    app_private.meal_id_by_code('main_beef')),
                 ('ml',       178,      app_private.product_id_by_upc('62891516502'),    app_private.meal_id_by_code('main_beef')),
                 ('ml',       178,      app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('main_beef')),
                 ('ml',       119,      app_private.product_id_by_upc('6047722102'),     app_private.meal_id_by_code('main_beef')),
                 ('ea',       1,        app_private.product_id_by_upc('77000414419'),    app_private.meal_id_by_code('main_beef')),
                 ('ml',       30,       app_private.product_id_by_upc('6810007852'),     app_private.meal_id_by_code('main_beef')),
                 ('ml',       15,       app_private.product_id_by_upc('5700000913'),     app_private.meal_id_by_code('main_beef')),
                 ('ml',       45,       app_private.product_id_by_upc('20490100000'),    app_private.meal_id_by_code('main_beef')),
                 ('tsp',      0.75,     app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('main_beef')),
                 ('tsp',      0.5,      app_private.product_id_by_upc('68113186234'),    app_private.meal_id_by_code('main_beef')),
                 ('tsp',      0.25,     app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('main_beef')),
                 ('ml',       60,       app_private.product_id_by_upc('5700000299'),     app_private.meal_id_by_code('main_beef')),
                 ('ml',       30,       app_private.product_id_by_upc('72636758456'),    app_private.meal_id_by_code('main_beef')),
                 ('ml',       15,       app_private.product_id_by_upc('6401312029'),     app_private.meal_id_by_code('main_beef')),
                
                 ('g',        80,       app_private.product_id_by_upc('6284721023'),     app_private.meal_id_by_code('s_vegetable')),
                 ('ml',       80,       app_private.product_id_by_upc('62773501731'),    app_private.meal_id_by_code('s_vegetable')),
                 ('tsp',      0.5,      app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('s_vegetable')),
                 ('tsp',      0.125,    app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('s_vegetable')),
                 ('oz',       14,       app_private.product_id_by_upc('68113186152'),    app_private.meal_id_by_code('s_vegetable')),
                 ('oz',       14,       app_private.product_id_by_upc('19056916660'),    app_private.meal_id_by_code('s_vegetable')),
                 ('oz',       14,       app_private.product_id_by_upc('19056916160'),    app_private.meal_id_by_code('s_vegetable')),
                 ('ea',       1,        app_private.product_id_by_upc('7315015201'),     app_private.meal_id_by_code('s_vegetable')),
                 ('ea',       0.5,      app_private.product_id_by_upc('20472200000'),    app_private.meal_id_by_code('s_vegetable')),
                 ('cup',      0.25,     app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('s_vegetable')),
                 ('ea',    1,        app_private.product_id_by_upc('33383651415'),     app_private.meal_id_by_code('s_vegetable')),
                
                 ('ml',       15,       app_private.product_id_by_upc('62773501730'),    app_private.meal_id_by_code('mm_pork_side')),
                 ('ea',       4,        app_private.product_id_by_upc('22132600000'),    app_private.meal_id_by_code('mm_pork_side')),
                 ('pkg',      1,        app_private.product_id_by_upc('62891567011'),    app_private.meal_id_by_code('mm_pork_side')),
                 ('cup',      1,        app_private.product_id_by_upc('60538892849'),    app_private.meal_id_by_code('mm_pork_side')),
                 ('cup',      0.5,      app_private.product_id_by_upc('3338345080'),     app_private.meal_id_by_code('mm_pork_side')),
                 ('ml',       80,       app_private.product_id_by_upc('62891582939'),    app_private.meal_id_by_code('mm_pork_side')),
                 ('cup',      0.33,     app_private.product_id_by_upc('5900001658'),     app_private.meal_id_by_code('mm_pork_side')),
                 ('little',   0,        app_private.product_id_by_upc('20490100000'),    app_private.meal_id_by_code('mm_pork_side')),
                 ('pinch',    0,        app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('mm_pork_side')),
                
                 ('cup',      2,        app_private.product_id_by_upc('62773502064'),    app_private.meal_id_by_code('sd_starches')),
                 ('tsp',      2,        app_private.product_id_by_upc('62773501730'),    app_private.meal_id_by_code('sd_starches')),
                 ('cup',      0.5,      app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('sd_starches')),
                 ('cup',      0.5,      app_private.product_id_by_upc('7315015201'),     app_private.meal_id_by_code('sd_starches')),
                 ('cup',      0.5,      app_private.product_id_by_upc('3338366002'),     app_private.meal_id_by_code('sd_starches')),
                 ('cup',      4,        app_private.product_id_by_upc('62891523568'),    app_private.meal_id_by_code('sd_starches')),
                 ('tsp',      1,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('sd_starches')),
                 ('tsp',      0.25,     app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('sd_starches')),
                 ('cup',      0.25,     app_private.product_id_by_upc('20490100000'),    app_private.meal_id_by_code('sd_starches')),
                
                 ('lb',       2,        app_private.product_id_by_upc('60580600134'),    app_private.meal_id_by_code('sd_potatoes')),
                 ('tbsp',     4,        app_private.product_id_by_upc('62773501731'),    app_private.meal_id_by_code('sd_potatoes')),
                 ('tsp',      2,        app_private.product_id_by_upc('68113186250'),    app_private.meal_id_by_code('sd_potatoes')),
                 ('tsp',      1.5,      app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('sd_potatoes')),
                 ('tsp',      0.25,     app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('sd_potatoes')),
                
                 ('cup',      0.5,      app_private.product_id_by_upc('72636758456'),    app_private.meal_id_by_code('mm_chicken_side')),
                 ('tsp',      0.5,      app_private.product_id_by_upc('68113186226'),    app_private.meal_id_by_code('mm_chicken_side')),
                 ('tsp',      1,        app_private.product_id_by_upc('68113186234'),    app_private.meal_id_by_code('mm_chicken_side')),
                 ('tsp',      1,        app_private.product_id_by_upc('68113186244'),    app_private.meal_id_by_code('mm_chicken_side')),
                 ('tsp',      1,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('mm_chicken_side')),
                 ('tsp',      1,        app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('mm_chicken_side')),
                 ('tbsp',     2,        app_private.product_id_by_upc('62773501730'),    app_private.meal_id_by_code('mm_chicken_side')),
                 ('lb',       3,        app_private.product_id_by_upc('62891582644'),    app_private.meal_id_by_code('mm_chicken_side')),
                
                 ('ml',       30,       app_private.product_id_by_upc('62773501730'),    app_private.meal_id_by_code('mm_beef_mix')),
                 ('cup',      0.75,     app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('mm_beef_mix')),
                 ('g',        681,      app_private.product_id_by_upc('62891582518'),    app_private.meal_id_by_code('mm_beef_mix')),
                 ('ea',       3,        app_private.product_id_by_upc('67929500051'),    app_private.meal_id_by_code('mm_beef_mix')),
                 ('tbsp',     1,        app_private.product_id_by_upc('68113186229'),    app_private.meal_id_by_code('mm_beef_mix')),
                 ('tsp',      2,        app_private.product_id_by_upc('62891566939'),    app_private.meal_id_by_code('mm_beef_mix')),
                 ('tsp',      2,        app_private.product_id_by_upc('6946791708'),     app_private.meal_id_by_code('mm_beef_mix')),
                 ('tsp',      0.5,      app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('mm_beef_mix')),
                 ('tsp',      0.5,      app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('mm_beef_mix')),
                 ('ea',       1,        app_private.product_id_by_upc('68113175984'),    app_private.meal_id_by_code('mm_beef_mix')),
                 ('ea',       1,        app_private.product_id_by_upc('67929500217'),    app_private.meal_id_by_code('mm_beef_mix')),
                 ('pack',     1,        app_private.product_id_by_upc('5830019684'),     app_private.meal_id_by_code('mm_beef_mix')),
                 ('ea',    1,        app_private.product_id_by_upc('33383651415'),     app_private.meal_id_by_code('mm_beef_mix')),
                 ('can',      1,        app_private.product_id_by_upc('5880766561'),     app_private.meal_id_by_code('mm_beef_mix')),
                 ('count',    1,        app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('mm_beef_mix')),
                 ('tbsp',     2,        app_private.product_id_by_upc('68113171310'),    app_private.meal_id_by_code('mm_beef_mix')),
                 ('count',    1,        app_private.product_id_by_upc('67929500217'),    app_private.meal_id_by_code('mm_beef_mix')),
                 ('tbsp',     0.5,      app_private.product_id_by_upc('6601314160'),     app_private.meal_id_by_code('mm_beef_mix')),
                
                 ('cup',      1,        app_private.product_id_by_upc('6840066260'),     app_private.meal_id_by_code('sauce')),
                 ('tbsp',     2,        app_private.product_id_by_upc('5900000342'),     app_private.meal_id_by_code('sauce')),
                 ('tsp',      1,        app_private.product_id_by_upc('5620076217'),     app_private.meal_id_by_code('sauce')),
                 ('tsp',      1,        app_private.product_id_by_upc('20495800000'),    app_private.meal_id_by_code('sauce')),
                
                 ('cup',      1,        app_private.product_id_by_upc('6840066260'),     app_private.meal_id_by_code('sauce_side')),
                 ('ml',       178,      app_private.product_id_by_upc('62891582830'),    app_private.meal_id_by_code('sauce_side')),
                 ('tbsp',     1,        app_private.product_id_by_upc('20490100000'),    app_private.meal_id_by_code('sauce_side')),
                 ('tbsp',     1,        app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('sauce_side')),
                 ('tsp',      1,        app_private.product_id_by_upc('20495800000'),    app_private.meal_id_by_code('sauce_side')),
                 ('tsp',      1,        app_private.product_id_by_upc('6284721023'),     app_private.meal_id_by_code('sauce_side')),
                 ('tsp',      0.25,     app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('sauce_side')),
                
                 ('cup',      4,        app_private.product_id_by_upc('6420013044'),     app_private.meal_id_by_code('main_fish')),
                 ('tbsp',     2,        app_private.product_id_by_upc('62891582939'),    app_private.meal_id_by_code('main_fish')),
                 ('g',        227,      app_private.product_id_by_upc('3338345080'),     app_private.meal_id_by_code('main_fish')),
                 ('ea',       1,        app_private.product_id_by_upc('3338360102'),     app_private.meal_id_by_code('main_fish')),
                 ('cup',      1,        app_private.product_id_by_upc('6047722102'),     app_private.meal_id_by_code('main_fish')),
                 ('cup',      0.25,     app_private.product_id_by_upc('5900001658'),     app_private.meal_id_by_code('main_fish')),
                 ('can',      2,        app_private.product_id_by_upc('6136243430'),     app_private.meal_id_by_code('main_fish')),
                 ('g',        188,      app_private.product_id_by_upc('62891575178'),    app_private.meal_id_by_code('main_fish')),
                 ('ea',       0.5,      app_private.product_id_by_upc('20472200000'),    app_private.meal_id_by_code('main_fish')),
                 ('tsp',      0.25,     app_private.product_id_by_upc('68113186253'),    app_private.meal_id_by_code('main_fish')),
                 ('tsp',      0.25,     app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('main_fish')),
                 ('pinch',    0,        app_private.product_id_by_upc('6620000429'),     app_private.meal_id_by_code('main_fish')),

                 ('can',      1,        app_private.product_id_by_upc('6136243430'),     app_private.meal_id_by_code('salad_sandwiches')),
                 ('tbsp',     4,        app_private.product_id_by_upc('6840066260'),     app_private.meal_id_by_code('salad_sandwiches')),
                 ('pinch',    0,        app_private.product_id_by_upc('6601000105'),     app_private.meal_id_by_code('salad_sandwiches')),
                 ('pinch',    0,        app_private.product_id_by_upc('62891583143'),    app_private.meal_id_by_code('salad_sandwiches')),
                 ('ea',       6,        app_private.product_id_by_upc('6034771116'),     app_private.meal_id_by_code('salad_sandwiches'));