npx postgraphile \
  --subscriptions \
  --watch \
  --dynamic-json \
  --classic-ids \
  --no-setof-functions-contain-nulls \
  --no-ignore-rbac \
  --no-ignore-indexes \
  --show-error-stack=json \
  --host 0.0.0.0 \
  --port 4000 \
  --extended-errors hint,detail,errcode \
  --export-schema-graphql schema.graphql \
  --graphiql "/" \
  --enhance-graphiql \
  --allow-explain \
  --cors \
  --enable-query-batching \
  --append-plugins @graphile-contrib/pg-simplify-inflector \
  --legacy-relations omit \
  --connection $DATABASE_URL \
  --jwt-token-identifier app.jwt_token  \
  --jwt-secret $JWT_SECRET \
  --default-role app_anonymous \
  --schema app