blank_issues_enabled: false
contact_links:
  - name: Other issues and discussion
    url: https://civictechfredericton.slack.com/archives/C0113KSL9R9
    about: For issues beyond the above, try our Slack workspace

