name: Test

on:
  push:
    branches: [ v2 ]
  pull_request:
    branches: [ v2 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.11.3]
    steps:
    - uses: actions/checkout@v4

    - name: Check typos in code
      run: |
        echo "Checking typos in code"
        pip3 install typos
        typos